Repository element-hq/element-x-android, pull requests merged in 2023-09, with the labels that each got.

#1363 Update app icon
  app/src/debug/res/drawable/ic_launcher_background.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/kotlin/io/element/android/x/icon/IconPreview.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/nightly/res/drawable/ic_launcher_background.xml
  app/src/release/res/drawable/ic_launcher_background.xml
  tools/lint/lint.xml
Labels: X-Release-Blocker

#1366 Sync strings
  features/analytics/impl/src/main/res/values-de/translations.xml
  features/analytics/impl/src/main/res/values-fr/translations.xml
  features/call/src/main/res/values-fr/translations.xml
  features/createroom/impl/src/main/res/values-fr/translations.xml
  features/ftue/impl/src/main/res/values-de/translations.xml
  features/ftue/impl/src/main/res/values-fr/translations.xml
  features/invitelist/impl/src/main/res/values-de/translations.xml
  features/invitelist/impl/src/main/res/values-fr/translations.xml
  features/login/impl/src/main/res/values-de/translations.xml
  features/login/impl/src/main/res/values-fr/translations.xml
  features/logout/api/src/main/res/values-fr/translations.xml
  features/messages/impl/src/main/res/values-de/translations.xml
  features/messages/impl/src/main/res/values-fr/translations.xml
  features/onboarding/impl/src/main/res/values-de/translations.xml
  features/onboarding/impl/src/main/res/values-fr/translations.xml
  features/poll/impl/src/main/res/values-de/translations.xml
  features/preferences/impl/src/main/res/values-de/translations.xml
  features/preferences/impl/src/main/res/values-fr/translations.xml
  features/preferences/impl/src/main/res/values-sk/translations.xml
  features/rageshake/api/src/main/res/values-de/translations.xml
  features/rageshake/api/src/main/res/values-fr/translations.xml
  features/rageshake/impl/src/main/res/values-de/translations.xml
  features/rageshake/impl/src/main/res/values-fr/translations.xml
  features/roomdetails/impl/src/main/res/values-de/translations.xml
  features/roomdetails/impl/src/main/res/values-fr/translations.xml
  features/roomlist/impl/src/main/res/values-de/translations.xml
  features/roomlist/impl/src/main/res/values-fr/translations.xml
  features/verifysession/impl/src/main/res/values-fr/translations.xml
  libraries/androidutils/src/main/res/values-fr/translations.xml
  libraries/eventformatter/impl/src/main/res/values-fr/translations.xml
  libraries/push/impl/src/main/res/values-de/translations.xml
  libraries/push/impl/src/main/res/values-fr/translations.xml
  libraries/ui-strings/src/main/res/values-de/translations.xml
  libraries/ui-strings/src/main/res/values-fr/translations.xml
  libraries/ui-strings/src/main/res/values-sk/translations.xml
  libraries/ui-strings/src/main/res/values/localazy.xml
  tests/uitests/src/test/kotlin/ui/S.kt
  tests/uitests/src/test/snapshots/images/ui_S_t[f.preferences.impl.notifications_null_InvalidNotificationSettingsViewDark_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.preferences.impl.notifications_null_InvalidNotificationSettingsViewight_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.theme.components.previews_null_DateTimepickers_TimePickerHorizontal_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.theme.components.previews_null_DateTimepickers_TimePickerVerticalPreviewDark_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.theme.components.previews_null_DateTimepickers_TimePickerVerticalPreviewLight_0_null,NEXUS_5,1.0,en].png
Labels: X-Release-Blocker

#1330 Show a room list decoration for notification setting applied
  features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomSummaryRow.kt
  features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/datasource/RoomListDataSource.kt
  features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/model/RoomListRoomSummary.kt
  features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/model/RoomListRoomSummaryProvider.kt
  features/roomlist/impl/src/test/kotlin/io/element/android/features/roomlist/impl/RoomListPresenterTests.kt
  libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/VectorIcons.kt
  libraries/designsystem/src/main/res/drawable/ic_mention.xml
  libraries/designsystem/src/main/res/drawable/ic_mute.xml
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/roomlist/RoomListService.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/roomlist/RoomSummary.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/roomlist/RoomSummaryDetailsFactory.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/roomlist/RoomSummaryListProcessor.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/roomlist/RustRoomListService.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/room/RoomSummaryFixture.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/roomlist/FakeRoomListService.kt
  samples/minimal/src/main/kotlin/io/element/android/samples/minimal/RoomListScreen.kt
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_2,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_3,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_4,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_5,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_6,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowDark_0_null_7,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_2,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_3,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_4,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_5,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_6,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.roomlist.impl.components_null_RoomSummaryRowLight_0_null_7,NEXUS_5,1.0,en].png
Labels: X-Release-Blocker, Z-Schedule

#1367 Iterate on onboarding and welcome screens.
  changelog.d/1363.misc
  libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/atoms/ElementLogoAtom.kt
  libraries/designsystem/src/main/res/drawable-night-xxhdpi/element_logo.png
  libraries/designsystem/src/main/res/drawable-night/onboarding_bg.png
  libraries/designsystem/src/main/res/drawable-xxhdpi/element_logo.png
  libraries/designsystem/src/main/res/drawable/element_logo.xml
  libraries/designsystem/src/main/res/drawable/onboarding_bg.png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.ftue.impl.welcome_null_WelcomeView-D-2_3_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.ftue.impl.welcome_null_WelcomeView-N-2_4_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-D-0_0_null_0,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-D-0_0_null_1,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-D-0_0_null_2,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-D-0_0_null_3,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-D-0_0_null_4,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-N-0_1_null_0,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-N-0_1_null_1,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-N-0_1_null_2,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-N-0_1_null_3,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.onboarding.impl_null_OnBoardingScreen-N-0_1_null_4,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomLarge-D_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomLarge-N_1_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomLargeNoBlurShadow-D_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomLargeNoBlurShadow-N_1_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomMedium-D_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomMedium-N_1_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomMediumNoBlurShadow-D_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.atoms_null_ElementLogoAtomMediumNoBlurShadow-N_1_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.pages_null_OnBoardingPage-D_0_null,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[l.designsystem.atomic.pages_null_OnBoardingPage-N_1_null,NEXUS_5,1.0,en].png
Labels: Z-NextRelease

#1386 Remove usage of async-uniffi
  changelog.d/1381.misc
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClientFactory.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/notificationsettings/RustNotificationSettingsService.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/RustMatrixRoom.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/sync/RustSyncService.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/timeline/RoomTimelineExtensions.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/timeline/RustMatrixTimeline.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/verification/RustSessionVerificationService.kt
Labels: Z-NextRelease

#1432 Install apk from the app - REQUEST_INSTALL_PACKAGES
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/media/local/AndroidLocalMediaActions.kt
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/media/viewer/MediaViewerView.kt
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/factories/event/TimelineItemContentMessageFactory.kt
  features/messages/impl/src/main/res/drawable/ic_apk_install.xml
  libraries/core/src/main/kotlin/io/element/android/libraries/core/mimetype/MimeTypes.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/media/RustMediaLoader.kt
  libraries/ui-strings/src/main/res/values/localazy.xml
  tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.media.viewer_null_MediaViewerView_0_null_6,NEXUS_5,1.0,en].png
  tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.media.viewer_null_MediaViewerView_0_null_7,NEXUS_5,1.0,en].png
Labels: Z-NextRelease
