Repository element-hq/element-x-android, pull requests merged in 2024-06, with the labels that each got.

#2976 matrix : update rust sdk to 0.2.23
  gradle/libs.versions.toml
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/room/MessageEventType.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/MessageEventType.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/RoomContentForwarder.kt
Labels: Z-NextRelease

#2977 Room : introduce RustRoomFactory and be more robust.
  features/messages/impl/src/test/kotlin/io/element/android/features/messages/impl/timeline/TimelineControllerTest.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/RustMatrixRoom.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/room/RustRoomFactory.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/roomlist/RoomListExtensions.kt
Labels: Z-NextRelease

#3105 Let GitHub generates the release notes
  .github/pull_request_template.md
  .github/release.yml
  .github/renovate.json
  .github/workflows/fork-pr-notice.yml
  .github/workflows/nightly.yml
  .github/workflows/sync-localazy.yml
  .github/workflows/sync-sas-strings.yml
  CONTRIBUTING.md
  app/build.gradle.kts
  docs/danger.md
  docs/nightly_build.md
  tools/danger/dangerfile.js
  tools/release/ReleaseNotesNightly.md
  tools/release/release.sh
  tools/towncrier/template.md
  towncrier.toml
Labels: PR-Build

#3106 Fix F-Droid reproducible build.
  tools/release/release.sh
Labels: PR-Build

#3107 Fix `@room` mentions crashing in debug builds
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/event/TimelineItemTextView.kt
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/mentions/MentionSpan.kt
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/mentions/MentionSpanProvider.kt
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/model/MarkdownTextEditorState.kt
  libraries/textcomposer/impl/src/test/kotlin/io/element/android/libraries/textcomposer/impl/model/MarkdownTextEditorStateTest.kt
Labels: PR-Bugfix

#3109 Auth : fix restore session when there is no network.
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClientFactory.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/auth/RustMatrixAuthenticationService.kt
Labels: PR-Bugfix
