Repository element-hq/element-x-android, pull requests merged in 2025-08, with the labels that each got.

#5126 Redirect FOSS user to Element Pro according to element .well-known file
  appnav/build.gradle.kts
  appnav/src/main/kotlin/io/element/android/appnav/RootFlowNode.kt
  features/login/api/src/main/kotlin/io/element/android/features/login/api/accesscontrol/AccountProviderAccessControl.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/accesscontrol/DefaultAccountProviderAccessControl.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/accesscontrol/ElementWellknownRetriever.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/changeserver/AccountProviderAccessException.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/changeserver/ChangeServerPresenter.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/changeserver/ChangeServerStateProvider.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/changeserver/ChangeServerView.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/changeserver/UnauthorizedAccountProviderException.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/error/ChangeServerError.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/error/ChangeServerErrorProvider.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/login/LoginModeView.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/resolver/network/ElementWellKnown.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/onboarding/OnBoardingPresenter.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/qrcode/scan/QrCodeScanPresenter.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/qrcode/scan/QrCodeScanStateProvider.kt
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/screens/qrcode/scan/QrCodeScanView.kt
  features/login/impl/src/main/res/values/localazy.xml
  features/login/impl/src/test/kotlin/io/element/android/features/login/impl/accesscontrol/DefaultAccountProviderAccessControlTest.kt
  features/login/impl/src/test/kotlin/io/element/android/features/login/impl/accesscontrol/FakeElementWellknownRetriever.kt
  features/login/impl/src/test/kotlin/io/element/android/features/login/impl/changeserver/ChangeServerPresenterTest.kt
  features/login/impl/src/test/kotlin/io/element/android/features/login/impl/screens/onboarding/OnBoardingPresenterTest.kt
  features/login/impl/src/test/kotlin/io/element/android/features/login/impl/screens/qrcode/scan/QrCodeScanPresenterTest.kt
  libraries/androidutils/src/main/kotlin/io/element/android/libraries/androidutils/system/SystemUtils.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/TestData.kt
  tests/uitests/src/test/snapshots/images/features.login.impl.changeserver_ChangeServerView_Day_4_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.changeserver_ChangeServerView_Night_4_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Day_0_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Day_1_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Day_2_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Day_3_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Day_4_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Night_0_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Night_1_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Night_2_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Night_3_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.login_LoginModeView_Night_4_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.screens.qrcode.scan_QrCodeScanView_Day_5_en.png
  tests/uitests/src/test/snapshots/images/features.login.impl.screens.qrcode.scan_QrCodeScanView_Night_5_en.png
Labels: PR-Misc

#5138 Fix cursor position in room list search
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/search/RoomListSearchView.kt
Labels: PR-Bugfix

#5089 Fix leaving the room not always dismissing the room screen
  appnav/src/main/kotlin/io/element/android/appnav/room/RoomFlowNode.kt
  libraries/core/src/main/kotlin/io/element/android/libraries/core/coroutine/Flow.kt
Labels: PR-Bugfix

#5157 Do not automatically initialize `DefaultVideoMetadataExtractor`'s data source
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/video/VideoMetadataExtractor.kt
Labels: Z-NextRelease, PR-Bugfix

#5186 Fix sending videos in Android 11 and lower
  app/proguard-rules.pro
Labels: PR-Bugfix

#5180 Add shortcut suggestions for rooms, remove then when leaving
  appnav/src/main/kotlin/io/element/android/appnav/LoggedInFlowNode.kt
  features/leaveroom/impl/build.gradle.kts
  features/leaveroom/impl/src/main/kotlin/io/element/android/features/leaveroom/impl/LeaveRoomPresenter.kt
  features/leaveroom/impl/src/test/kotlin/io/element/android/features/leaveroom/impl/LeaveBaseRoomPresenterTest.kt
  features/messages/impl/build.gradle.kts
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/messagecomposer/MessageComposerPresenter.kt
  features/messages/impl/src/test/kotlin/io/element/android/features/messages/impl/messagecomposer/MessageComposerPresenterTest.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/MatrixClient.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/room/RoomMembersState.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/FakeMatrixClient.kt
  libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/media/InitialsAvatarBitmapGenerator.kt
  libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/room/MatrixRoomMembers.kt
  libraries/matrixui/src/test/kotlin/io/element/android/libraries/matrix/ui/room/RoomMembersTest.kt
  libraries/push/api/build.gradle.kts
  libraries/push/api/src/main/kotlin/io/element/android/libraries/push/api/notifications/NotificationBitmapLoader.kt
  libraries/push/api/src/main/kotlin/io/element/android/libraries/push/api/notifications/conversations/NotificationConversationService.kt
  libraries/push/impl/build.gradle.kts
  libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/DefaultNotificationBitmapLoader.kt
  libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/conversations/DefaultNotificationConversationService.kt
  libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/notifications/conversations/DefaultNotificationConversationServiceTest.kt
  libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/notifications/factories/FakeIntentProvider.kt
  libraries/push/test/src/main/kotlin/io/element/android/libraries/push/test/notifications/conversations/FakeNotificationConversationService.kt
  libraries/push/test/src/main/kotlin/io/element/android/libraries/push/test/notifications/push/FakeNotificationBitmapLoader.kt
  libraries/ui-strings/src/main/res/values/localazy.xml
  tests/uitests/src/test/snapshots/images/libraries.matrix.ui.media_InitialsAvatarBitmapGenerator_Day_0_en.png
  tests/uitests/src/test/snapshots/images/libraries.matrix.ui.media_InitialsAvatarBitmapGenerator_Night_0_en.png
Labels: PR-Feature

#5198 Ensure that only one DataStore is active for the same file.
  libraries/fullscreenintent/impl/src/main/kotlin/io/element/android/libraries/fullscreenintent/impl/FullScreenIntentPermissionsPresenter.kt
  libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultPreferencesDataStoreFactory.kt
Labels: PR-Bugfix

#5086 Handle preference stores corruption by clearing them
  app/src/main/kotlin/io/element/android/x/initializer/CrashInitializer.kt
  features/lockscreen/impl/build.gradle.kts
  features/lockscreen/impl/src/main/kotlin/io/element/android/features/lockscreen/impl/storage/PreferencesLockScreenStore.kt
  features/migration/impl/build.gradle.kts
  features/migration/impl/src/main/kotlin/io/element/android/features/migration/impl/DefaultMigrationStore.kt
  features/rageshake/impl/build.gradle.kts
  features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/crash/PreferencesCrashDataStore.kt
  features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/crash/VectorUncaughtExceptionHandler.kt
  features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/di/RageshakeBindings.kt
  features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/rageshake/PreferencesRageshakeDataStore.kt
  features/rageshake/impl/src/test/kotlin/io/element/android/features/rageshake/impl/crash/VectorUncaughtExceptionHandlerTest.kt
  gradle.properties
  libraries/androidutils/build.gradle.kts
  libraries/androidutils/src/main/kotlin/io/element/android/libraries/androidutils/preferences/DefaultPreferencesCorruptionHandlerFactory.kt
  libraries/featureflag/impl/build.gradle.kts
  libraries/featureflag/impl/src/main/kotlin/io/element/android/libraries/featureflag/impl/PreferencesFeatureFlagProvider.kt
  libraries/permissions/impl/build.gradle.kts
  libraries/permissions/impl/src/main/kotlin/io/element/android/libraries/permissions/impl/DefaultPermissionsStore.kt
  libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultAppPreferencesStore.kt
  libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultPreferencesDataStoreFactory.kt
  libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/store/DefaultPushDataStore.kt
  libraries/pushstore/impl/build.gradle.kts
  libraries/pushstore/impl/src/main/kotlin/io/element/android/libraries/pushstore/impl/DefaultUserPushStoreFactory.kt
  libraries/pushstore/impl/src/main/kotlin/io/element/android/libraries/pushstore/impl/UserPushStoreDataStore.kt
  libraries/pushstore/impl/src/main/kotlin/io/element/android/libraries/pushstore/impl/clientsecret/DataStorePushClientSecretStore.kt
  libraries/pushstore/impl/src/test/kotlin/io/element/android/libraries/pushstore/impl/UserPushStoreDataStoreTest.kt
  services/analytics/impl/build.gradle.kts
  services/analytics/impl/src/main/kotlin/io/element/android/services/analytics/impl/store/AnalyticsStore.kt
  tests/detekt-rules/src/main/kotlin/io/element/android/detektrules/ByPreferencesDataStoreRule.kt
  tests/detekt-rules/src/main/kotlin/io/element/android/detektrules/ElementRuleSetProvider.kt
Labels: PR-Bugfix

#5205 Try following KSP incremental best practices on `anvilcodegen`
  anvilcodegen/src/main/kotlin/io/element/android/anvilcodegen/ContributesNodeProcessor.kt
Labels: PR-Build

#5215 AnalyticsOptInStateProvider does not need to have an injected constructor
  features/analytics/impl/src/main/kotlin/io/element/android/features/analytics/impl/AnalyticsOptInStateProvider.kt
Labels: PR-Misc

#5223 Use variable bitrate mode when transcoding to ensure compatibility with old devices
  libraries/androidutils/src/main/kotlin/io/element/android/libraries/androidutils/media/VideoCompressorHelper.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/ThumbnailFactory.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressor.kt
Labels: PR-Bugfix

#5233 Revert "Try following KSP incremental best practices on `anvilcodegen`"
  anvilcodegen/src/main/kotlin/io/element/android/anvilcodegen/ContributesNodeProcessor.kt
Labels: PR-Build

#5236 [a11y] Add content descriptions to room list item indicators
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/components/RoomSummaryRow.kt
  libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/atomic/atoms/UnreadIndicatorAtom.kt
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeViewA11y_en.png
Labels: A11y, PR-Change
