Repository element-hq/element-x-android, pull requests merged in 2025-07, with the labels that each got.

#4960 Update min api level to 33 for Element enterprise
  .github/workflows/quality.yml
  .github/workflows/scripts/maestro/local-recording.sh
  README.md
  features/home/impl/src/test/kotlin/io/element/android/features/home/impl/roomlist/RoomListViewTest.kt
  features/preferences/impl/src/test/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsViewTest.kt
  features/roomdetails/impl/src/test/kotlin/io/element/android/features/roomdetails/impl/securityandprivacy/SecurityAndPrivacyViewTest.kt
  libraries/dateformatter/impl/src/test/kotlin/io/element/android/libraries/dateformatter/impl/DefaultDateFormatterFrTest.kt
  libraries/dateformatter/impl/src/test/kotlin/io/element/android/libraries/dateformatter/impl/DefaultDateFormatterTest.kt
  libraries/mediaupload/impl/src/test/kotlin/io/element/android/libraries/mediaupload/impl/AndroidMediaPreProcessorTest.kt
  libraries/mediaviewer/impl/src/test/kotlin/io/element/android/libraries/mediaviewer/impl/details/MediaDetailsBottomSheetTest.kt
  libraries/mediaviewer/impl/src/test/kotlin/io/element/android/libraries/mediaviewer/impl/viewer/MediaViewerViewTest.kt
  libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/notifications/channels/NotificationChannelsTest.kt
  plugins/src/main/kotlin/Versions.kt
  tools/release/release.sh
Labels: PR-Build

#4962 Change : sync moderation and safety preferences with server
  appnav/src/main/kotlin/io/element/android/appnav/LoggedInFlowNode.kt
  appnav/src/main/kotlin/io/element/android/appnav/loggedin/MediaPreviewConfigMigration.kt
  appnav/src/test/kotlin/io/element/android/appnav/loggedin/MediaPreviewConfigMigrationTest.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/roomlist/RoomListPresenter.kt
  features/joinroom/impl/src/main/kotlin/io/element/android/features/joinroom/impl/JoinRoomPresenter.kt
  features/joinroom/impl/src/main/kotlin/io/element/android/features/joinroom/impl/di/JoinRoomModule.kt
  features/joinroom/impl/src/test/kotlin/io/element/android/features/joinroom/impl/JoinRoomPresenterTest.kt
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/protection/TimelineProtectionPresenter.kt
  features/messages/impl/src/test/kotlin/io/element/android/features/messages/impl/timeline/protection/TimelineProtectionPresenterTest.kt
  features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsPresenter.kt
  features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsState.kt
  features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsStateProvider.kt
  features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsView.kt
  features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/advanced/MediaPreviewConfigStateStore.kt
  features/preferences/impl/src/test/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsPresenterTest.kt
  features/preferences/impl/src/test/kotlin/io/element/android/features/preferences/impl/advanced/AdvancedSettingsViewTest.kt
  features/preferences/impl/src/test/kotlin/io/element/android/features/preferences/impl/advanced/FakeMediaPreviewConfigStateStore.kt
  features/preferences/impl/src/test/kotlin/io/element/android/features/preferences/impl/advanced/MediaPreviewConfigStateStoreTest.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/MatrixClient.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/media/MediaPreviewConfig.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/media/MediaPreviewService.kt
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/media/MediaPreviewValue.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/di/SessionMatrixModule.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/media/RustMediaPreviewService.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/FakeMatrixClient.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/media/FakeMediaPreviewService.kt
  libraries/preferences/api/src/main/kotlin/io/element/android/libraries/preferences/api/store/AppPreferencesStore.kt
  libraries/preferences/impl/src/main/kotlin/io/element/android/libraries/preferences/impl/store/DefaultAppPreferencesStore.kt
  libraries/preferences/test/src/main/kotlin/io/element/android/libraries/preferences/test/InMemoryAppPreferencesStore.kt
  libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/DefaultNotifiableEventResolver.kt
  libraries/push/impl/src/test/kotlin/io/element/android/libraries/push/impl/notifications/DefaultNotifiableEventResolverTest.kt
  tests/uitests/src/test/snapshots/images/features.preferences.impl.advanced_AdvancedSettingsViewDark_6_en.png
  tests/uitests/src/test/snapshots/images/features.preferences.impl.advanced_AdvancedSettingsViewDark_7_en.png
  tests/uitests/src/test/snapshots/images/features.preferences.impl.advanced_AdvancedSettingsViewLight_6_en.png
  tests/uitests/src/test/snapshots/images/features.preferences.impl.advanced_AdvancedSettingsViewLight_7_en.png
Labels: PR-Change

#4964 Home navigation bar
  features/home/impl/build.gradle.kts
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomeEvents.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomeNavigationBarItem.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomePresenter.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomeState.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomeStateProvider.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/HomeView.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/components/RoomListContentView.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/components/RoomListTopBar.kt
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/roomlist/RoomListStateProvider.kt
  features/home/impl/src/test/kotlin/io/element/android/features/home/impl/HomePresenterTest.kt
  gradle/libs.versions.toml
  libraries/featureflag/api/src/main/kotlin/io/element/android/libraries/featureflag/api/FeatureFlags.kt
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_10_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_11_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_12_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_13_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_14_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_3_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_4_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_5_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_6_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_7_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_8_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Day_9_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_10_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_11_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_12_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_13_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_14_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_3_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_4_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_5_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_6_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_7_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_8_en.png
  tests/uitests/src/test/snapshots/images/features.home.impl_HomeView_Night_9_en.png
Labels: PR-Wip

#4976 Update dependency org.matrix.rustcomponents:sdk-android to v25.7.3
  gradle/libs.versions.toml
Labels: PR-Dependencies

#4975 [a11y] Ensure that the focus is not lost when the send button state change
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/TextComposer.kt
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/components/SendButton.kt
  libraries/textcomposer/impl/src/main/kotlin/io/element/android/libraries/textcomposer/components/VoiceMessageRecorderButton.kt
  libraries/ui-strings/src/main/res/values/localazy.xml
Labels: A11y, PR-Misc

#4981 misc (tracing) : add new TraceLogPack.Notification
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/tracing/TraceLogPack.kt
  libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/tracing/TraceLogPacksMapping.kt
Labels: PR-Misc

#4993 fix ( room list) : rebuild with filteredSummaries to avoid bad state
  features/home/impl/src/main/kotlin/io/element/android/features/home/impl/datasource/RoomListDataSource.kt
Labels: PR-Bugfix

#5008 Keep video rotation metadata when transcoding
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressor.kt
  libraries/mediaupload/impl/src/test/kotlin/io/element/android/libraries/mediaupload/impl/VideoStrategyFactoryTest.kt
Labels: PR-Bugfix

#5018 Replace video transcoder with Media3 Transformer
  gradle/libs.versions.toml
  libraries/mediaupload/impl/build.gradle.kts
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/AndroidMediaPreProcessor.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressor.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressorConfig.kt
  libraries/mediaupload/impl/src/test/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressorConfigFactoryTest.kt
  libraries/mediaupload/impl/src/test/kotlin/io/element/android/libraries/mediaupload/impl/VideoStrategyFactoryTest.kt
Labels: PR-Misc

#5043 Grammar fixes for docs and comments
  docs/_developer_onboarding.md
  docs/notifications.md
  features/login/impl/src/main/kotlin/io/element/android/features/login/impl/login/LoginHelper.kt
Labels: PR-Doc

#5040 misc (room id) : add room id regex pattern to match new versions
  libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/core/MatrixPatterns.kt
  libraries/matrix/api/src/test/kotlin/io/element/android/libraries/matrix/api/core/MatrixPatternsTest.kt
Labels: PR-Misc

#5042 Note how to switch back to the published SDK after building locally
  docs/_developer_onboarding.md
Labels: PR-Doc

#5044 Fix `toPlainText` where `<ol start='n'>` tags appear
  libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/messages/ToPlainText.kt
  libraries/matrixui/src/test/kotlin/io/element/android/libraries/matrix/ui/messages/ToPlainTextTest.kt
Labels: PR-Bugfix

#5064 Disable Element Call Maestro tests for the time being
  .maestro/tests/roomList/timeline/messages/text.yaml
  .maestro/tests/roomList/timeline/timeline.yaml
Labels: PR-Build

#5046 [a11y] Improve accessibility on avatar when creating a room.
  features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomView.kt
Labels: A11y, PR-Misc

#5039 Make sure we clean up the pre-processed and uploaded media
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewPresenter.kt
  features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/attachments/preview/AttachmentsPreviewView.kt
  features/messages/impl/src/test/kotlin/io/element/android/features/messages/impl/attachments/AttachmentsPreviewPresenterTest.kt
  libraries/mediaupload/api/src/main/kotlin/io/element/android/libraries/mediaupload/api/MediaPreProcessor.kt
  libraries/mediaupload/api/src/main/kotlin/io/element/android/libraries/mediaupload/api/MediaSender.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/AndroidMediaPreProcessor.kt
  libraries/mediaupload/test/src/main/kotlin/io/element/android/libraries/mediaupload/test/FakeMediaPreProcessor.kt
Labels: PR-Bugfix

#5068 Calculate video output size taking into account portrait mode
  libraries/androidutils/src/main/kotlin/io/element/android/libraries/androidutils/bitmap/Bitmap.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/ImageCompressor.kt
  libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/impl/VideoCompressorConfig.kt
Labels: PR-Bugfix

#5079 Make sure we display errors when we create a recovery key and it fails
  features/securebackup/impl/src/main/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupPresenter.kt
  features/securebackup/impl/src/main/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupState.kt
  features/securebackup/impl/src/main/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupStateMachine.kt
  features/securebackup/impl/src/main/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupStateProvider.kt
  features/securebackup/impl/src/main/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupView.kt
  features/securebackup/impl/src/test/kotlin/io/element/android/features/securebackup/impl/setup/SecureBackupSetupPresenterTest.kt
  libraries/matrix/test/src/main/kotlin/io/element/android/libraries/matrix/test/encryption/FakeEncryptionService.kt
  tests/uitests/src/test/snapshots/images/features.securebackup.impl.setup_SecureBackupSetupViewChange_Day_5_en.png
  tests/uitests/src/test/snapshots/images/features.securebackup.impl.setup_SecureBackupSetupViewChange_Night_5_en.png
  tests/uitests/src/test/snapshots/images/features.securebackup.impl.setup_SecureBackupSetupView_Day_5_en.png
  tests/uitests/src/test/snapshots/images/features.securebackup.impl.setup_SecureBackupSetupView_Night_5_en.png
Labels: PR-Bugfix

#5085 Fix crash when trying to get active notifications
  libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/ActiveNotificationsProvider.kt
Labels: PR-Bugfix
